import os 
from os import system

system('clear')
# Data Types

integerNum = 4 # integer type with 32 bits => 4 bytes
longNum = 234567890123344 # long type with 64 bits => 8 bytes
floatNum = 2.54 # float type with 32 bits => 4 bytes
stringSingle = 'My dog is a beautiful one' # string class (single quotes)
stringDouble = "My dog is a beautiful one" # string class (double quotes)


def multiply(n1, n2):
    result = n1 * n2
    return result


num1 = int(input("Please input the first number >> "))
num2 = int(input("Please input a second number >> "))

multiply = num1 * num2

print(f"The result of {multiply} was generated by the multiply() function")




def addition(n1, n2, n3):
    result = n1 + n2 + n3
    return result

num1 = int(input("Please enter the first number in this equation >> "))    
num2 = int(input("Please enter the second number in this equation >> "))  
num3 = int(input("Please enter the third number in this equation >> "))  

addition = num1 + num2+ num3

print(f"The result of {addition} is the correct answer.")